/**
 * Public API for the Wallet Companion browser extension.
 *
 * @example
 * ```typescript
 * if (window.WalletCompanion?.isInstalled) {
 *   await window.WalletCompanion.registerWallet({
 *     name: 'My Wallet',
 *     url: 'https://wallet.example.com',
 *     protocols: ['openid4vp'],
 *   });
 * }
 * ```
 */
export interface WalletCompanionInterface {
    /**
     * Semantic version of the extension (e.g. `"1.2.3"`).
     */
    readonly version: string;

    /**
     * Always `true` when the extension is active.
     *
     * Since `window.WalletCompanion` is undefined when the extension is not installed,
     * use optional chaining: `window.WalletCompanion?.isInstalled`
     */
    readonly isInstalled: boolean;

    /**
     * Protocol identifiers supported by at least one registered wallet.
     *
     * Use this to check if any wallet can handle a specific protocol before initiating a flow.
     *
     * @example
     * ```typescript
     * if (window.WalletCompanion?.supportedProtocols.includes('openid4vp')) {
     *   // At least one wallet supports OpenID4VP
     * }
     * ```
     */
    readonly supportedProtocols: readonly string[];

    /**
     * Register a wallet with the extension.
     *
     * Idempotent: if the URL is already registered, returns the existing wallet.
     *
     * @throws {Error} If validation fails or registration times out (5s)
     *
     * @example
     * ```typescript
     * const { wallet, alreadyRegistered } = await window.WalletCompanion.registerWallet({
     *   name: 'My Wallet',
     *   url: 'https://wallet.example.com',
     *   protocols: ['openid4vp'],
     * });
     * ```
     */
    registerWallet(walletInfo: WalletRegistrationInput): Promise<WalletRegistrationResult>;

    /**
     * Check if a wallet URL is already registered.
     *
     * Use this to avoid prompting users to register a wallet they've already added.
     *
     * @throws {Error} If check times out (5s)
     */
    isWalletRegistered(url: string): Promise<boolean>;

    /**
     * Get the extension's attestation public key.
     *
     * Returns the JWK of the ephemeral P-256 key used for Tier 2 attestation.
     * Returns `null` if no key has been generated yet.
     *
     * The key rotates each browser session and provides extension-attested
     * binding for WIA requests.
     */
    getAttestationKey(): Promise<{ kid: string; publicKeyJwk: JsonWebKey } | null>;

    /**
     * Sign a WIA challenge with the extension's attestation key.
     *
     * The wallet frontend calls this during WIA generation to prove
     * the request originates from a browser with the extension installed.
     *
     * @param challenge - The nonce from the wallet backend's WIA challenge endpoint.
     * @returns Compact JWS (ES256, typ: extension-attestation+jwt)
     * @throws {Error} If the attestation key is not available
     */
    signWiaChallenge(challenge: string): Promise<string>;
}

/**
 * Input for {@link WalletCompanionInterface.registerWallet}.
 */
export type WalletRegistrationInput = {
    /**
     * Display name shown in the wallet selector UI.
     */
    name: string;

    /**
     * Base URL where the wallet receives requests (e.g. `https://wallet.example.com`).
     * Must use `http:` or `https:` scheme.
     */
    url: string;

    /**
     * URL to the wallet's icon. Fetched and converted to a data-URI during registration.
     * Recommended: square image, at least 64x64px.
     */
    icon?: string | null;

    /**
     * Short tagline shown below the wallet name in the selector UI.
     */
    description?: string | null;

    /**
     * Brand color used for UI accents. Must be a 6-digit hex code (e.g. `#FF0000`).
     */
    color?: string | null;

    /**
     * Protocol identifiers this wallet supports (e.g. `['openid4vp']`).
     * Only wallets matching the requested protocol are shown in the selector.
     * Format: lowercase alphanumeric with hyphens.
     */
    protocols?: string[] | null;
}

/**
 * Result from {@link WalletCompanionInterface.registerWallet}.
 */
export type WalletRegistrationResult = {
    /**
     * `true` if the wallet is now registered (whether newly added or already existed).
     */
    success: boolean;

    /**
     * `true` if the wallet URL was already registered. The existing wallet is returned unchanged.
     */
    alreadyRegistered: boolean;

    /**
     * The registered wallet with server-generated fields populated.
     * Only present when `success` is `true`.
     */
    wallet?: Wallet;
}

/**
 * A wallet registered with the extension.
 */
export type Wallet = {
    /**
     * Unique identifier generated by the extension. Use this to reference the wallet in API calls.
     * Not derived from the URL—two wallets with different IDs may share the same URL across browser profiles.
     */
    id: string;

    /**
     * Display name shown in the wallet selector UI.
     */
    name: string;

    /**
     * Base URL where the wallet receives requests.
     */
    url: string;

    /**
     * Data-URI of the wallet's icon, converted from the original URL during registration.
     * Falls back to a generated icon if none was provided.
     */
    icon: string;

    /**
     * Short tagline shown below the wallet name.
     */
    description?: string | null;

    /**
     * Brand color for UI accents (6-digit hex, e.g. `#FF0000`).
     */
    color?: string | null;

    /**
     * Protocol identifiers this wallet supports.
     */
    protocols?: string[] | null;

    /**
     * Whether the wallet is active. Disabled wallets are hidden from the selector.
     */
    enabled: boolean;

    /**
     * `true` if the wallet was registered automatically (e.g. via a website's registration prompt)
     * rather than manually by the user.
     */
    autoRegistered?: boolean | null;

    /**
     * Origin of the page that triggered auto-registration (e.g. `https://wallet.example.com`).
     */
    registeredFrom?: string | null;

    /**
     * ISO 8601 timestamp of when the wallet was registered.
     */
    registeredAt?: string | null;
}
